name: Deploy to Workers

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: publish
        uses: cloudflare/wrangler-action@1.1.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
