name: Build site

on: push
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudflare/wrangler-action@1.1.0
      with: 
        apiKey: 6BXfv3BNG4-w14MXF_kpINxI-l5_gOeW84UdRxx2  
    - name: Build Workers script
      run: wrangler publish
